### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by forever139** [HT524/500LineorLess_CN#1]
http://docs.python-requests.org/en/master/
<img width="621" alt="error" src="https://cloud.githubusercontent.com/assets/3293537/18034024/c632465c-6d64-11e6-8280-2932f164a86c.png">

**Comment by skhe** [comment]
哈哈，是我的疏忽。requests 库我最近也一直在用，我在做后端开发实习。多谢您的指正。我自己检查都没发现。谢谢！ @forever139

**Comment by skhe** [comment]
已改正。 @forever139
