### ISSUE TITLE
可视化编程工具（Blockcode）

### ISSUE THREAD

**Issue by wizardforcel** [HT524/500LineorLess_CN#14]
http://m.blog.csdn.net/article/details?id=51898028

**Comment by skhe** [comment]
好的，谢谢您。我看了那篇文章，感觉翻译得很好。我把链接加到对应表了。另外，见到大佬好激动。

**Comment by wizardforcel** [comment]
还有这个 python 模板引擎：

http://www.jianshu.com/p/b5d4aa45e771
http://www.jianshu.com/p/d6551dfacd58
