### ISSUE TITLE
请求认领《内存中的图数据库》一章

### ISSUE THREAD

**Issue by yanwang10** [HT524/500LineorLess_CN#16]
试译请见：https://github.com/yanwang10/500LineorLess_CN/blob/master/%E5%86%85%E5%AD%98%E4%B8%AD%E7%9A%84%E5%9B%BE%E6%95%B0%E6%8D%AE%E5%BA%93%20Dagoba:%20an%20in-memory%20graph%20database/%E5%86%85%E5%AD%98%E4%B8%AD%E7%9A%84%E5%9B%BE%E6%95%B0%E6%8D%AE%E5%BA%93.md

**Comment by skhe** [comment]
仔细读了试译的部分，挺好的。已加入认领表，大家一起努力，把 500lines 翻译出来，共勉。

**Comment by yanwang10** [comment]
好的，收到！
