### ISSUE TITLE
How to commit a task

### ISSUE THREAD

**Issue by NickNYU** [HT524/500LineorLess_CN#17]
Hi 

目前我正在学习Clustering by Consensus，想着可以贡献一份自己的力量，请问怎样认领任务，以及相应的要求

谢谢

**Comment by skhe** [comment]
@NickNYU  fork 后在自己的分支上翻译，翻译工作有较大进展时可以创建 pull request，没问题的话，我们会 merge。认真翻译就行，有问题别人也会给你提 issues。
