### ISSUE TITLE
请问现在还招人一起翻译吗？

### ISSUE THREAD

**Issue by WaterWan** [HT524/500LineorLess_CN#21]
您好！我是在校大二的学生，专业是软件工程，在学习python的时候看到了这个项目，希望能加入其中，之前没有参与过翻译项目，python也不是我的主语言，但是希望能参与其中，请问是否还有机会？如果可以的话能不能留一个联系方式？谢谢！

**Comment by skhe** [comment]
@WaterWan 欢迎参与。要是打算参与翻译，可以选择想要翻译的章节，fork项目，参考已有的中文章节，建立自己的工作目录，在该目录下进行翻译工作。当有较大进展时，可以发起合并请求，翻译质量不错的话，我们会合并进来。

**Comment by WaterWan** [comment]
请问是否有交流群之类或者论坛之类的讨论之处吗？或者说如果我有不明白的地方可以找谁请教比较好呢？谢谢啦！

**Comment by skhe** [comment]
翻译工作的交流群或者论坛，暂时还没有。目前是大问题 提 issues 或者发邮件给我，小问题谷歌解决。
